tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "shivammathur/php"
brew "allure"
brew "awscli"
brew "brew-php-switcher"
brew "php", restart_service: true
brew "composer"
cask "chromedriver"
